# Config values used by dotfiles.

## Users
[users."RShirohara@proton.me"]
name = "Ray Shirohara"
email = "RShirohara@proton.me"
signingKey = "E7321F26D8EACF39!"

## Dependencies
[dependency.linux.pacman]
packages = [
  "age",
  "aws-vault",
  "carapace-bin",
  "ghq",
  "git-credential-oauth",
  "git-delta",
  "git",
  "helix",
  "nushell",
  "serie",
  "sops",
  "starship",
]

[dependency.linux.homebrew]
taps = []
brews = [
  "age",
  "aws-vault",
  "carapace",
  "ghq",
  "git-credential-libsecret",
  "git-credential-oauth",
  "git-delta",
  "git",
  "helix",
  "nushell",
  "serie",
  "sops",
  "starship",
]
