# Users.
[users."RShirohara@proton.me"]
name = "Ray Shirohara"
email = "RShirohara@proton.me"
signingKey = "E7321F26D8EACF39!"

# Dependencies.
[dependency.darwin.homebrew]

[dependency.linux.homebrew]
