# Users.
[users."RShirohara@proton.me"]
name = "Ray Shirohara"
email = "RShirohara@proton.me"
signingKey = "E7321F26D8EACF39!"

# Dependencies.
[dependency.darwin.homebrew]
taps = []
formulae = [
  { name = "age" },
  { name = "carapace" },
  { name = "ghq" },
  { name = "git" },
  { name = "git-credential-oauth" },
  { name = "git-delta" },
  { name = "nushell" },
  { name = "starship" },
]
casks = []

[dependency.linux.homebrew]
taps = [
  { name = "age" },
  { name = "carapace" },
  { name = "ghq" },
  { name = "git" },
  { name = "git-credential-libsecret" },
  { name = "git-credential-oauth" },
  { name = "git-delta" },
  { name = "nushell" },
  { name = "starship" },
]
formulae = []
