theme = "github_dark"

[editor]
bufferline = "always"
color-modes = true
scroll-lines = 5

[editor.statusline]
left = ["mode", "spacer", "version-control", "diagnostics"]
center = ["spinner"]
right = [
  "position",
  "primary-selection-length",
  "file-encoding",
  "file-line-ending",
  "file-type",
]

[editor.cursor-shape]
normal = "bar"
insert = "bar"
select = "underline"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
tabpad = "Â·"

[editor.indent-guides]
render = true
skip-levels = 1

[editor.soft-wrap]
enable = true
